service: ${file(./sls-variables.yml):service}

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-api-cloudfront

custom:
  apigwBinary:
    types:
      - '*/*'
  apiCloudFront:
    domain:
      - ${file(./sls-variables.yml):domain}
    certificate: ${file(./sls-variables.yml):certificate}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(./sls-variables.yml):region}
  environment:
    NODE_ENV: "production"
    NODE_SLS: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY